language: python
matrix:
  fast_finish: true
  include:
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.4"
      env: TOXENV=lint
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
install: pip install -U setuptools tox coveralls
script: tox
after_success: coveralls
